### ISSUE TITLE
Pass Vulkan instance from Godot to IREE

### ISSUE THREAD

**Issue by RechieKho** [RechieKho/iree.gd#11]
Creating another vulkan instance is a footgun and I can already feel it as IREE context keeps killing itself spontaneously. I have no idea how to access Godot's VkInstance from GDExtension, and I'm not even sure it is exported or not.

~~Nightmare, nightmare~~

**Comment by RechieKho** [comment]
Tried to wrap vulkan device through RenderDevice of gdextension. Results Godot crash in libc.so. Code is in wrap-vulkan branch.

**Comment by RechieKho** [comment]
Confirmed. Will submit PR for godot engine to export vulkan instance process address.

**Comment by RechieKho** [comment]
Too bad, the solution is considered as a hack. So now I try using volk to load the vulkan library ourselves and get that ` vkGetInstanceAddrProc`. Unfortunately, it is a null pointer after initialization. Not sure why this happens.

**Comment by fire** [comment]
Can you point me to the line of code loading this?

**Comment by RechieKho** [comment]
https://github.com/RechieKho/iree.gd/blob/main/src/iree_device.cpp#L188

**Comment by RechieKho** [comment]
I guess this is completed.
