### ISSUE TITLE
When compiling iree cannot find binaries

### ISSUE THREAD

**Issue by fire** [RechieKho/iree.gd#15]
Iree complains that the flat buffer compiler doesn't exist, when I want to compile iree.

**Comment by RechieKho** [comment]
Iree should have its own flatbuffer compiler being compiled...? Does it scream about something with the tools directory?

**Comment by fire** [comment]
I fetched iree from github, people don't store binaries in github..

**Comment by RechieKho** [comment]
There are iree's binary tools on its release page, but unfortunately it is not for windows.

**Comment by fire** [comment]
I'm on the mac currently.

**Comment by RechieKho** [comment]
This is beyond my knowledge although macos is fork from unix

**Comment by fire** [comment]
https://github.com/openxla/iree/blob/main/build_tools/python_deploy/build_macos_packages.sh 

This is how ci is applied.

**Comment by RechieKho** [comment]
Ok. I've update some CMake options, I guess it won't complain now as it compiles the flatbuffer compiler itself.
