### ISSUE TITLE
Unable to use iree.gd on Windows

### ISSUE THREAD

**Issue by fire** [RechieKho/iree.gd#37]
### Issue description

I'm unable to use iree.gd on Windows.

### Steps to reproduce

1. download iree.gd
2. start on windows with godot engine

### Using a released version?

No

### What OS? Any other relevant information? (iree.gd revision, System information)

Windows, Nvidia, https://github.com/RechieKho/iree.gd/commit/9dbb380569c62d3fa685e49fa6cfa9a83e3fbd28

**Comment by RechieKho** [comment]
I need someone to test this for me... But it seems like after I considered the CPU arch to the library naming, the GitHub workflow kind of broke, and did not export the compiled file, so I can't get people to test it without compiling the project.

**Comment by RechieKho** [comment]
https://drive.google.com/file/d/16W4crIrPKBnVRX-Yx5ELZrBeO8RJWgQg/view?usp=sharing

I made a sample with containing the appropriate library. It is still quite big so I upload to google drive.

**Comment by fire** [comment]
@RechieKho ready for testing?

**Comment by RechieKho** [comment]
> @RechieKho ready for testing?

Sure, if you want to test it immediately, then you could [download the library](https://github.com/RechieKho/iree.gd/actions/runs/7549218780) and extract it into the sample folder. Or you could wait till I publish it.

**Comment by RechieKho** [comment]
Still not working. Error status: `0x000012f`

Maybe I need to turn on [`CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`](https://cmake.org/cmake/help/latest/variable/CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS.html).

**Comment by RechieKho** [comment]
> @RechieKho ready for testing?

@fire I guess it is ready now.
You can download [the sample from the release](https://github.com/RechieKho/iree.gd/releases/tag/v0.0.1-alpha1)

**Comment by RechieKho** [comment]
A friend from Godot server discord tested it out. The extension is loaded, but fail to create IREE context. I'm speculating it is due to outdated `.vmfb`.

<img width="543" alt="Screenshot 2024-01-17 at 3 55 21 PM" src="https://github.com/RechieKho/iree.gd/assets/50512341/bced8c65-daa7-474b-a272-ebe2eeda4d86">

**Comment by RechieKho** [comment]
Works on iFire's supercomputer with iree.gd `v0.0.0-alpha2`. So this issue is fixed.

https://github.com/RechieKho/iree.gd/assets/50512341/e2a4e88b-9205-406b-9960-eb1f773e6060
