### ISSUE TITLE
 CMake Error with Metal does not exist on Linux

### ISSUE THREAD

**Issue by fire** [RechieKho/iree.gd#38]
### Issue description

```
CMake Error at CMakeLists.txt:168 (target_link_libraries):
  Target "iree-gd.linux.release.x86_64" links to:

    iree::hal::drivers::metal::registration

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.



-- Generating done (0.8s)
```

### Steps to reproduce

1. Go to https://github.com/RechieKho/iree.gd
2. Check the latest action on https://github.com/RechieKho/iree.gd/commit/786e2c6070f99d0cc30b0fb2614b5f8a76bd00d7
3. View the logs

### Minimal reproduction project (For SDK or engine issues)

Not related.

### Using a released version?

No

### What OS? Any other relevant information? (iree.gd revision, System information)

Windows, Nvidia

**Comment by RechieKho** [comment]
Remember I say I forgot to update CMakeLists?  (https://github.com/RechieKho/iree.gd/issues/21)
This is kind of the result...

It will be fixed very soon TM.

**Comment by RechieKho** [comment]
Noice, it is done.
