### ISSUE TITLE
Handle godot precision=double

### ISSUE THREAD

**Issue by fire** [RechieKho/iree.gd#8]
Todo check

**Comment by RechieKho** [comment]
When converting the `Vector*` variants, I did use `REAL_T_IS_DOUBLE` to make sure whether it is a `double` or a `float`. The algorithm only accept conversion between type with same byte size or larger, anything else results an error. If I accidentally convert from bigger type to smaller type, it must be a mistake.

**Comment by RechieKho** [comment]
After the rewrite, it only support arrays that stores primitive type (int and floats). So we don't need to care about double precision for now.
